Use dependency injection
drupal-graphql/graphql-search-api pull request #17
Opened 2018-12-20 02:00 UTC by el7cosmos

2018-12-20 12:42 UTC, joaogarin commented
Thanks for the PR: will try have a look at it as soon as possible

2018-12-23 04:00 UTC, duartegarin commented
Hi guys,
Currently away but I will try to review the PR this week.
Thanks

2018-12-29 11:46 UTC, joaogarin requested changes
Thanks for the PR I gave it a test and it looks good! 👍 I think it improves the code quite a lot so we should merge this. just minor coding standards stuff that [coder](https://www.drupal.org/project/coder) is telling me about but nothing big. If you cant do these changes I can also include them np :) Thanks for the pull request

2018-12-29 11:46 UTC, joaogarin commented on src/Plugin/GraphQL/Derivers/SearchAPIDocumentTypeDeriver.php
> +  public function __construct(EntityTypeManagerInterface $entity_type_manager) {
Here we should now replace the comment with the proper PHPDoc signature for the arguments in the constructor.
Something like : 
```
/**
 * @param \Drupal\Core\Entity\EntityTypeManagerInterface $entity_type_manager
 *   The entity type manager service.
 */
```

2018-12-29 11:46 UTC, joaogarin commented on src/Plugin/GraphQL/Derivers/SearchAPIFieldDeriver.php
> +  public function __construct(EntityTypeManagerInterface $entity_type_manager) {
Same as above we can now include the PHPDoc signature here withe information on the params passed to the constructor.

2018-12-29 19:14 UTC, joaogarin approved these changes
Looks good to me 👍

2018-12-31 03:50 UTC, merged

2018-12-31 03:50 UTC, duartegarin commented
Thank you @el7cosmos